[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ultimateocr"
version = "0.1.0"
description = "Next-generation OCR Engine"
readme = "README.md"
requires-python = ">=3.10"

authors = [
    {name = "UltimateOCR Team"}
]

dependencies = [
    "numpy",
    "opencv-python",
    "torch",
    "torchvision",
    "albumentations",
    "PyYAML",
    "Pillow",
    "tqdm"
]

[tool.setuptools.packages.find]
include = ["ultimateocr*"]