
version: 1

datasets:

  icdar2015:

    name: ICDAR 2015

    task:
      - text_detection
      - text_recognition

    license: Research Only

    homepage: https://rrc.cvc.uab.es/?ch=4

    download: https://rrc.cvc.uab.es/?ch=4&com=downloads

    format: icdar2015

    splits:

      train:

        images: datasets/raw/icdar2015/train/images

        annotations: datasets/raw/icdar2015/train/annotations

      test:

        images: datasets/raw/icdar2015/test/images

        annotations: datasets/raw/icdar2015/test/annotations
